### ISSUE TITLE
求安装教程

### ISSUE THREAD

**Issue by 2lifetop** [Layne666/oneindex#1]
我也想做一个像你一样的，但是绑定不了账号，能出一个简单的教程吗

**Comment by Layne666** [comment]
好的，我写一下吧~

**Comment by Layne666** [comment]
报错信息是什么呢？😂

1. client_id、client_secret配的对吗？
2. 你redirect_uri改了吗？在AdminController里
3. 世纪互联账号支持外链分享吗？

**Comment by 2lifetop** [comment]
谢谢，我已经会安装了，为了防止我以后忘了我写了个教程挂我博客上了，介意我留下你的网站和这个代码地址吗？

**Comment by Layne666** [comment]
不介意的，我很荣幸也很感谢你能这样做~

**Comment by DaBoSAMA** [comment]
请问这个简单的教程在哪里QAQ
