### ISSUE TITLE
使用picgo web api上传报错

### ISSUE THREAD

**Issue by valetzx** [Layne666/oneindex#13]
上传了，但没完全上传。后台没改
![image](https://user-images.githubusercontent.com/45054400/158013326-9fc66ed5-49ac-43f8-bb49-3e9df05ce311.png)
部署地址：https://pigone.000webhostapp.com/ 
![image](https://user-images.githubusercontent.com/45054400/158013351-7ea69f0b-5719-489b-9819-4d13133e8b10.png)

**Comment by Layne666** [comment]
![image](https://user-images.githubusercontent.com/34464278/171012286-032b54d1-92e7-4501-be6e-eb1584f6bfd8.png)
上传失败的话，可以把最新的日志内容发出来我瞅瞅~

**Comment by valetzx** [comment]
已解决，感谢
