### ISSUE TITLE
请问可以自定义走原OneDrive

### ISSUE THREAD

**Issue by hucstar** [Layne666/oneindex#2]
我说以前很流畅的成功安装，现在怎么不成呢，原来又出了个“世纪互联”版，有办法用您这个魔改版走OneDrive原版吗？

**Comment by hucstar** [comment]
搞定啦！😄

**Comment by KarlcxChina** [comment]
请问是如何解决的？

**Comment by Ayx03** [comment]
https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id={$client_id}&redirect_uri={$redirect_uri}
